# log.filters = [ "debug" ]
# file = "~/.config/npingler/default.nix"
# profile.file = "~/.local/state/nix/profiles/profile"
# profile.extra_switch_args = []
# registry.pin = false
# registry.pin_root = false
# channels.pin = false
# nix.extra_args.nix = []
# nix.extra_args."nix build" = []
# nix.extra_args."nix eval" = []
# nix.extra_args."nix-env --set" = []
